### ISSUE TITLE
Fix travis

### ISSUE THREAD

**Issue by mscherer** [OSAS/ansible-role-middleman_builder#6]
Since the travis is broken, because the role can't build in travis, we need to either makeit run on debian, or remove the offending lines.

**Comment by duck-rh** [comment]
Maybe I can have a look :-)

**Comment by mscherer** [comment]
Sure, make a PR. That's likely mostly about packages names. You can see the failed build of the other PR.

**Comment by duck-rh** [comment]
fixed by PR#8
